// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp_oplvaONHSdrd1Ez4IJK0fvgskBRuTE',
    appId: '1:354386791551:web:c76ccf7ff2e3c82ad9434a',
    messagingSenderId: '354386791551',
    projectId: 'firstprojecttest-40ea4',
    authDomain: 'firstprojecttest-40ea4.firebaseapp.com',
    storageBucket: 'firstprojecttest-40ea4.appspot.com',
    measurementId: 'G-3RHCC88VCW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBid06Lcdkz4593unaobnvBuOgFQHrzcXE',
    appId: '1:354386791551:android:5a3168a5722c6df8d9434a',
    messagingSenderId: '354386791551',
    projectId: 'firstprojecttest-40ea4',
    storageBucket: 'firstprojecttest-40ea4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2REW4F3YDULGrbP3T8l4yA8lAnFoESAU',
    appId: '1:354386791551:ios:2b6ba2c36728e1bad9434a',
    messagingSenderId: '354386791551',
    projectId: 'firstprojecttest-40ea4',
    storageBucket: 'firstprojecttest-40ea4.appspot.com',
    iosClientId:
        '354386791551-12b5l557j9encnf878rkr53iju4b31do.apps.googleusercontent.com',
    iosBundleId: 'com.example.myproject',
  );
}
